"""AI build-time scaffolding (PRD §5.1) — profile.json -> proposed dbt code.

Two tiers, by design (PRD §3 "automate what's safe, curate what matters"):

  • DETERMINISTIC baseline (no key needed): mechanical snake_case staging model +
    schema.yml with not_null/unique on every derived candidate key. This alone
    makes a brand-new dataset land in a clean, typed, tested staging layer.

  • LLM ENHANCEMENT (needs a key): feeds the profile to Claude to get a better
    staging model (unit standardization, sensible casts, junk filters), richer but
    conservative tests, and *proposed* mart stubs with explanatory comments.

Output is written to `datasets/<name>/scaffold/` for HUMAN REVIEW — it never
overwrites the curated dbt models. The boundary is the point: the agent proposes;
a human reviews, corrects, and commits.

`--write` additionally INSTALLS the deterministic staging model + tests into the
dbt project and merges a `raw.<table>` entry into the sources file — collapsing the
cold-start wiring into one command. Staging is safe to auto-wire (it's 1:1 with
source); MARTS are never auto-installed, because their semantics are curated.

    python -m engine.scaffold anage
    python -m engine.scaffold mydata --write     # generate + wire staging into dbt
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

import yaml

from .config import (
    DATASETS_DIR,
    DBT_PROJECT_DIR,
    has_anthropic_key,
    load_dataset_config,
)

STAGING_DIR = DBT_PROJECT_DIR / "models" / "staging"
SOURCES_YML = STAGING_DIR / "_sources.yml"

# A small set of identifiers that can't be used bare as column aliases in DuckDB.
_RESERVED = {
    "order", "group", "select", "from", "where", "table", "column", "all",
    "any", "as", "case", "check", "default", "desc", "asc", "primary", "references",
}


def snake_case(name: str) -> str:
    """Generic column-name normalizer: lower, units kept, punctuation -> _."""
    s = name.strip().lower()
    s = s.replace("/", " ").replace("-", " ")
    s = re.sub(r"[^\w\s]", " ", s)        # drop parens, %, etc.
    s = re.sub(r"\s+", "_", s.strip())
    s = re.sub(r"_+", "_", s).strip("_")
    if not s:
        s = "col"
    if s[0].isdigit():
        s = "c_" + s
    if s in _RESERVED:
        s = s + "_"
    return s


def _dedupe(names: list[str]) -> list[str]:
    seen: dict[str, int] = {}
    out: list[str] = []
    for n in names:
        if n in seen:
            seen[n] += 1
            out.append(f"{n}_{seen[n]}")
        else:
            seen[n] = 0
            out.append(n)
    return out


def _load_profile(dataset: str) -> dict:
    p = DATASETS_DIR / dataset / "profile.json"
    if not p.exists():
        raise FileNotFoundError(
            f"No profile at {p}. Run `python -m engine.profile {dataset}` first."
        )
    return json.loads(p.read_text(encoding="utf-8"))


# ─────────────────────────────────────────────────────────────────────────────
# Deterministic baseline
# ─────────────────────────────────────────────────────────────────────────────

def deterministic_staging(profile: dict, dataset: str) -> tuple[str, str]:
    """Return (model_sql, schema_yml) — a safe, mechanical staging scaffold.

    The model is tagged with `config(schema='<dataset>_staging')` so it lands in
    the dataset's own schema, and reads from the dataset's raw source."""
    table = profile["table"]
    cols = profile["columns"]
    aliases = _dedupe([snake_case(c["name"]) for c in cols])

    select_lines = []
    width = max((len(c["name"]) for c in cols), default=10) + 4
    for c, alias in zip(cols, aliases):
        src = '"' + c["name"].replace('"', '""') + '"'
        select_lines.append(f"        {src:<{width}} as {alias},")
    select_lines[-1] = select_lines[-1].rstrip(",")  # last column, no trailing comma

    model_sql = (
        "-- GENERATED by engine/scaffold.py (deterministic baseline) — REVIEW ME.\n"
        f"-- 1:1 staging for {dataset}_raw.{table}: snake_case rename only. Add casts,\n"
        "-- unit standardization, and junk-row filters before committing.\n"
        # Node name is dataset-prefixed (globally unique across datasets); `alias`
        # keeps the warehouse relation clean as <dataset>_staging.stg_<table>.
        f"{{{{ config(schema='{dataset}_staging', alias='stg_{table}') }}}}\n\n"
        "with source as (\n"
        f"    select * from {{{{ source('{dataset}', '{table}') }}}}\n"
        "),\n\n"
        "renamed as (\n"
        "    select\n"
        + "\n".join(select_lines)
        + "\n    from source\n"
        ")\n\n"
        "select * from renamed\n"
    )

    key_cols = [a for c, a in zip(cols, aliases) if c.get("is_candidate_key")]
    yml_lines = [
        "version: 2",
        "",
        "models:",
        f"  - name: {dataset}__stg_{table}",
        f'    description: "GENERATED scaffold for {dataset}_raw.{table} — review before committing."',
        "    columns:",
    ]
    for c, alias in zip(cols, aliases):
        yml_lines.append(f"      - name: {alias}")
        tests = []
        if c.get("is_candidate_key"):
            tests = ["not_null", "unique"]
        elif c.get("null_rate", 1.0) == 0.0:
            tests = ["not_null"]
        if tests:
            yml_lines.append("        data_tests:")
            yml_lines += [f"          - {t}" for t in tests]
    schema_yml = "\n".join(yml_lines) + "\n"
    return model_sql, schema_yml


# ─────────────────────────────────────────────────────────────────────────────
# LLM enhancement
# ─────────────────────────────────────────────────────────────────────────────

_SYSTEM = """\
You are the BUILD-TIME SCAFFOLDING layer of a trust-first analytics framework.
You are handed a JSON profile of ONE raw table (column names, types, null rates,
cardinality, candidate keys, sample values). You propose dbt (DuckDB dialect) code
for a HUMAN to review — you are not the runtime, and your output is never executed
without review.

Return a SINGLE JSON object, no markdown, with EXACTLY these keys:

{
  "staging_sql": "<a dbt model: with source as (select * from {{ source('raw','<table>') }}), renamed as (...) select ... — snake_case every column, cast where the raw type is wrong, standardize units in comments, add a junk-row filter in a trailing WHERE, and add a derived natural key/name if obvious. Reference source columns by their EXACT raw name in double quotes.>",
  "schema_yml": "<dbt schema.yml v2 for the staging model: a short description per column, and CONSERVATIVE tests — not_null/unique only on columns the profile shows are actually non-null/unique; accepted_values ONLY for low-cardinality coded columns whose full value set you can see in sample_values. Do NOT over-test.>",
  "proposed_marts": [
    {
      "name": "mart_<something>",
      "rationale": "<one line: what business question this answers>",
      "sql": "<a dbt mart stub reading {{ ref('stg_<table>') }}, with -- comments explaining the modeling choices and any assumptions. It is OK to leave clearly-marked TODOs for the human.>"
    }
  ]
}

Rules (dataset = the profile's `dataset` field):
  • DuckDB SQL. Raw: {{ source('<dataset>', '<table>') }}. Staging: refer to it as
    {{ ref('<dataset>__stg_<table>') }} (model names are dataset-prefixed for
    global uniqueness).
  • Begin the staging model with
    {{ config(schema='<dataset>_staging', alias='stg_<table>') }} and each mart with
    {{ config(schema='<dataset>_marts', alias='<mart_basename>') }} — the alias keeps
    the warehouse relation clean while the model name stays prefixed.
  • Name each proposed mart "<dataset>__mart_<something>" (the prefixed model name).
  • Tests must be JUSTIFIED by the profile. A test that would fail on the real
    data is worse than no test. When unsure, omit it.
  • Propose 1-3 marts, each a genuinely useful business rollup — not just
    "select *". Mart SEMANTICS are the human's call, so explain your reasoning in
    comments and surface assumptions explicitly.
  • Output ONLY the JSON object.
"""


def _strip_json(text: str) -> str:
    t = text.strip()
    if t.startswith("```"):
        t = re.sub(r"^```(?:json)?\s*", "", t)
        t = re.sub(r"\s*```$", "", t)
    m = re.search(r"\{[\s\S]*\}", t)
    return m.group(0) if m else t


def llm_scaffold(profile: dict) -> dict:
    from ._llm import complete
    from .config import get_ai_settings

    user = (
        "Here is the profile of the raw table to scaffold. Propose staging + tests "
        "+ marts for human review.\n\n"
        + json.dumps(profile, indent=2, default=str)
    )
    text, usage = complete(
        system=_SYSTEM, user=user, model=get_ai_settings().model_l2, max_tokens=6000,
    )
    print(f"  [llm] model={usage.model} in={usage.input_tokens} out={usage.output_tokens} "
          f"cache_read={usage.cache_read_input_tokens}")
    return json.loads(_strip_json(text), strict=False)


_MULTI_SYSTEM = """\
You are the BUILD-TIME SCAFFOLDING layer of a trust-first analytics framework.
You are handed a JSON profile of SEVERAL related raw tables (each with columns,
types, null rates, candidate keys, samples) PLUS a list of DERIVED relationships
(parent/child/column/cardinality). A deterministic per-table staging model has
already been generated — your job is to propose JOIN-BASED marts across the
tables, for a HUMAN to review. You are not the runtime.

Return a SINGLE JSON object, no markdown:

{
  "proposed_marts": [
    {
      "name": "mart_<something>",
      "rationale": "<one line: the cross-table business question this answers>",
      "sql": "<a dbt mart reading {{ ref('stg_<table>') }} for the staging models, joining across the relationships. RESPECT cardinality: pre-aggregate a 1:many child to the parent's grain BEFORE joining so you don't fan out rows. Add -- comments for modeling choices and assumptions.>"
    }
  ]
}

Rules (dataset = the profile's `dataset` field):
  • DuckDB SQL. Reference staging models as {{ ref('<dataset>__stg_<table>') }}
    (model names are dataset-prefixed for global uniqueness).
  • Begin each mart with {{ config(schema='<dataset>_marts', alias='<mart_basename>') }}
    and name it "<dataset>__mart_<something>".
  • Propose 1-3 marts that are only possible by JOINING the tables (that's the value).
  • Honor the derived cardinalities to avoid fan-out (pre-aggregate children).
  • Mart semantics are the human's call — explain reasoning in comments. Output ONLY JSON.
"""


def llm_propose_join_marts(profile: dict) -> dict:
    from ._llm import complete
    from .config import get_ai_settings

    user = ("Here is the multi-table profile (tables + derived relationships). Propose "
            "join-based marts for human review.\n\n" + json.dumps(profile, indent=2, default=str))
    text, usage = complete(system=_MULTI_SYSTEM, user=user,
                           model=get_ai_settings().model_l2, max_tokens=6000)
    print(f"  [llm] model={usage.model} in={usage.input_tokens} out={usage.output_tokens}")
    return json.loads(_strip_json(text), strict=False)


# ─────────────────────────────────────────────────────────────────────────────
# Install into the dbt project (--write): staging model + tests + sources entry
# ─────────────────────────────────────────────────────────────────────────────

def ensure_source_entry(dataset: str, table: str, *, description: str = "") -> bool:
    """Idempotently add a `<table>` entry under the dataset's own source block
    (source name = dataset, schema = `<dataset>_raw`). Returns True if a new entry
    was added. Each dataset gets its own source block so raw tables are namespaced
    by dataset and never collide across datasets."""
    if SOURCES_YML.exists():
        doc = yaml.safe_load(SOURCES_YML.read_text(encoding="utf-8")) or {}
    else:
        doc = {}
    doc.setdefault("version", 2)
    sources = doc.setdefault("sources", [])
    src = next((s for s in sources if s.get("name") == dataset), None)
    if src is None:
        src = {"name": dataset, "schema": f"{dataset}_raw",
               "description": f"Raw landing tables for the {dataset} dataset (engine/ingest.py).",
               "tables": []}
        sources.append(src)
    tables = src.setdefault("tables", [])
    if any(t.get("name") == table for t in tables):
        return False
    tables.append({"name": table, "description": description or f"Raw {table} table."})
    STAGING_DIR.mkdir(parents=True, exist_ok=True)
    header = ("# dbt sources — per-dataset raw landing zones written by engine/ingest.py.\n"
              "# Managed by `scaffold --write`; edit descriptions freely.\n")
    SOURCES_YML.write_text(
        header + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, default_flow_style=False),
        encoding="utf-8")
    return True


def install_staging(dataset: str, table: str, scaffold_dir: Path, *, force: bool = False) -> list[str]:
    """Copy the deterministic staging model + tests from the scaffold dir into the
    dbt project, and merge the sources entry. Returns a list of human-readable
    actions taken. Refuses to overwrite an existing model unless force=True."""
    STAGING_DIR.mkdir(parents=True, exist_ok=True)
    actions: list[str] = []
    node = f"{dataset}__stg_{table}"
    pairs = [(f"{node}.sql", f"{node}.sql"), (f"_{node}.yml", f"_{node}.yml")]
    for src_name, dst_name in pairs:
        src = scaffold_dir / src_name
        dst = STAGING_DIR / dst_name
        if not src.exists():
            continue
        if dst.exists() and not force:
            actions.append(f"SKIP {dst_name} (already in models/staging — use --force to overwrite)")
            continue
        shutil.copyfile(src, dst)
        actions.append(f"wrote models/staging/{dst_name}")

    added = ensure_source_entry(dataset, table)
    actions.append(f"added {dataset}.{table} to _sources.yml" if added
                   else f"{dataset}.{table} already in _sources.yml")
    return actions


# ─────────────────────────────────────────────────────────────────────────────
# Driver
# ─────────────────────────────────────────────────────────────────────────────

def _write_proposed_marts(out: Path, marts: list[dict]) -> None:
    for m in marts:
        name = m.get("name") or "mart_proposed"
        body = (
            f"-- PROPOSED MART: {name}\n"
            f"-- Rationale: {m.get('rationale','(none given)')}\n"
            "-- Mart semantics are a human decision — review, correct, then move\n"
            "-- into dbt_project/models/marts/ to make it real.\n\n"
            + (m.get("sql") or "").strip() + "\n"
        )
        (out / f"{name}.proposed.sql").write_text(body, encoding="utf-8")
        print(f"  [ok] proposed mart          -> {out / f'{name}.proposed.sql'}  ({m.get('rationale','')[:60]})")


def scaffold(dataset: str, *, write: bool = False, force: bool = False) -> Path:
    cfg = load_dataset_config(dataset)
    profile = _load_profile(dataset)
    out = cfg.dir / "scaffold"
    out.mkdir(parents=True, exist_ok=True)

    # profile.json holds a `tables` list (one entry for single-table datasets).
    table_profiles = profile.get("tables") or []
    relationships = profile.get("relationships") or []

    # 1. Deterministic baseline + (optional) install — per table.
    for tp in table_profiles:
        table = tp["table"]
        node = f"{dataset}__stg_{table}"  # globally-unique dbt model name
        base_sql, base_yml = deterministic_staging(tp, dataset)
        (out / f"{node}.sql").write_text(base_sql, encoding="utf-8")
        (out / f"_{node}.yml").write_text(base_yml, encoding="utf-8")
        print(f"  [ok] deterministic staging  -> {node}.sql (+ tests)")
        if write:
            print(f"  Installing stg_{table} into the dbt project:")
            for action in install_staging(dataset, table, out, force=force):
                print(f"    - {action}")

    if relationships:
        print(f"\n  {len(relationships)} cross-table relationship(s) detected — the LLM step "
              "will propose join marts across them.")
    if write:
        print(f"\n  Staging wired in. Next: curate marts from {out}/*.proposed.sql, "
              f"then `python run.py up {dataset}`.")

    if not has_anthropic_key():
        print("\n  (No Anthropic key - wrote the deterministic baseline only. Add a key for "
              "LLM-proposed marts, unit standardization, and inferred tests.)")
        return out

    # 2. LLM enhancement. Single-table keeps the richer staging+marts proposal;
    #    multi-table focuses on JOIN marts across the inferred relationships.
    try:
        if len(table_profiles) == 1:
            result = llm_scaffold(table_profiles[0])
            table = table_profiles[0]["table"]
            if result.get("staging_sql"):
                (out / f"stg_{table}.llm.sql").write_text(
                    "-- LLM-PROPOSED staging — review against the deterministic baseline.\n\n"
                    + result["staging_sql"].strip() + "\n", encoding="utf-8")
                print(f"  [ok] LLM staging proposal   -> stg_{table}.llm.sql")
            if result.get("schema_yml"):
                (out / f"_stg_{table}.llm.yml").write_text(result["schema_yml"].strip() + "\n", encoding="utf-8")
            _write_proposed_marts(out, result.get("proposed_marts") or [])
        else:
            result = llm_propose_join_marts(profile)
            _write_proposed_marts(out, result.get("proposed_marts") or [])
    except Exception as exc:
        print(f"\n  [warn] LLM scaffolding failed ({exc}). Deterministic baseline still written.")
        return out

    print(f"\n  Review the proposals in {out}. Deterministic files are safe as-is; the "
          ".llm/.proposed files are suggestions to curate before committing.")
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Scaffold dbt staging + tests + proposed marts from profile.json.")
    ap.add_argument("dataset", help="dataset name (folder under datasets/)")
    ap.add_argument("--write", action="store_true",
                    help="install the staging model + sources entry into the dbt project")
    ap.add_argument("--force", action="store_true",
                    help="with --write, overwrite an existing staging model")
    args = ap.parse_args(argv)
    scaffold(args.dataset, write=args.write, force=args.force)
    return 0


if __name__ == "__main__":
    sys.exit(main())
