-- GENERATED by engine/scaffold.py (deterministic baseline) — REVIEW ME.
-- 1:1 staging for nba_raw.games_index: snake_case rename only. Add casts,
-- unit standardization, and junk-row filters before committing.
{{ config(schema='nba_staging', alias='stg_games_index') }}

with source as (
    select * from {{ source('nba', 'games_index') }}
),

renamed as (
    select
        "game_id"          as game_id,
        "game_date"        as game_date,
        "season_year"      as season_year,
        "matchup"          as matchup,
        "home"             as home,
        "away"             as away,
        "team_id_home"     as team_id_home,
        "team_id_away"     as team_id_away,
        "team_name_home"   as team_name_home,
        "team_name_away"   as team_name_away,
        "winner"           as winner,
        "pts_home"         as pts_home,
        "pts_away"         as pts_away,
        "margin"           as margin,
        "min"              as min,
        "odds_home"        as odds_home,
        "odds_away"        as odds_away
    from source
)

select * from renamed
